name: Dry Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/12 * * *'
  push:
    branches: [ "main" ]

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: dryrun
      uses: hashi-strawb/tfc-ephemeral-workspace-check@test
      with:
        tfe-token: ${{ secrets.TFE_TOKEN }}
        config: dryrun.hcl