name: Fix Non-Compliant Workspaces

on:
  workflow_dispatch:

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: fix
      uses: hashi-strawb/tfc-ephemeral-workspace-check@test
      with:
        tfe-token: ${{ secrets.TFE_TOKEN }}
        config: non-dryrun.hcl