name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: foo
      uses: hashi-strawb/tfc-ephemeral-workspace-check@test
      with:
        tfe-token: ${{ secrets.TFE_TOKEN }}
        config: dryrun.hcl